export type AcceptanceCase = [input: string, accepted: boolean, label: string];

const cases: Record<string, AcceptanceCase[]> = {
  "only-a.ts": [
    ["", true, "empty string"],
    ["a", true, "single a"],
    ["aaa", true, "aaa"],
    ["b", false, "single b"],
    ["ab", false, "ab"],
    ["ba", false, "ba"],
    ["aab", false, "aab"],
  ],
  "ends-in-ab.ts": [
    ["ab", true, "ab"],
    ["aab", true, "aab"],
    ["bab", true, "bab"],
    ["ababab", true, "ababab"],
    ["a", false, "single a"],
    ["b", false, "single b"],
    ["ba", false, "ba"],
    ["", false, "empty string"],
    ["aba", false, "aba"],
  ],
  "ends-in-ab-or-ba.ts": [
    ["ab", true, "ab"],
    ["ba", true, "ba"],
    ["aab", true, "aab"],
    ["bba", true, "bba"],
    ["abab", true, "abab"],
    ["baba", true, "baba"],
    ["abba", true, "abba"],
    ["", false, "empty string"],
    ["a", false, "single a"],
    ["b", false, "single b"],
    ["aa", false, "aa"],
    ["bb", false, "bb"],
    ["abb", false, "abb"],
    ["baa", false, "baa"],
  ],
  "odd-zeros-or-ends-with-two-ones.ts": [
    ["0", true, "only one zero (matches 0(00)*)"],
    ["000", true, "only three zeros (matches 0(00)*)"],
    ["11", true, "ends with 11 (matches Σ*11)"],
    ["011", true, "ends with 11 (matches Σ*11)"],
    ["1011", true, "ends with 11 (matches Σ*11)"],
    ["1111", true, "four ones (matches Σ*11)"],
    ["", false, "empty string"],
    ["1", false, "single 1"],
    ["10", false, "one zero but not part of 0(00)* branch"],
    ["00", false, "even number of zeros"],
    ["10110", false, "even number of zeros, doesn't end in 11"],
  ],
  "odd-zeros-or-ends-with-two-ones-thompson.ts": [
    ["0", true, "only one zero (matches 0(00)*)"],
    ["000", true, "only three zeros (matches 0(00)*)"],
    ["11", true, "ends with 11 (matches Σ*11)"],
    ["011", true, "ends with 11 (matches Σ*11)"],
    ["1011", true, "ends with 11 (matches Σ*11)"],
    ["1111", true, "four ones (matches Σ*11)"],
    ["", false, "empty string"],
    ["1", false, "single 1"],
    ["10", false, "one zero but not part of 0(00)* branch"],
    ["00", false, "even number of zeros"],
    ["10110", false, "even number of zeros, doesn't end in 11"],
  ],
  "a-divisible-by-2-or-3.ts": [
    // count-of-a divisible by 2
    ["", true, "empty (0 a's, div by 2 and 3)"],
    ["aa", true, "aa (2 a's, div 2)"],
    ["aaaa", true, "aaaa (4 a's, div 2)"],
    ["bb", true, "bb (0 a's)"],
    // count-of-a divisible by 3
    ["aaa", true, "aaa (3 a's, div 3)"],
    ["aaaaaa", true, "aaaaaa (6 a's, div both)"],
    // neither
    ["a", false, "a (1 a)"],
    ["aaaaa", false, "aaaaa (5 a's)"],
    ["bab", false, "bab (1 a, not div)"],
  ],
  "thompson.ts": [
    ["", true, "0 zeros (div by 3)"],
    ["1", true, "0 zeros (div by 3)"],
    ["111", true, "0 zeros (div by 3)"],
    ["000", true, "3 zeros (div by 3)"],
    ["1011010", true, "3 zeros (div by 3)"],
    ["0", false, "1 zero"],
    ["00", false, "2 zeros"],
    ["110", false, "1 zero"],
    ["1001", false, "2 zeros"],
  ],
};

export default cases;
